name: hive_core
description: A new flutter plugin project.
version: 0.0.1
author:
# homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.1"

dependencies:
  flutter:
    sdk: flutter

  #
  # I/O, Cache & Databases
  #
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  hive: ^2.0.4 # local storage
  sqflite: ^2.0.0+3 # local storage

  #
  # Firebase packages
  #
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  # firebase_auth_web: ^1.3.1
  firebase_storage: ^8.1.3
  firebase_messaging: ^10.0.2
  firebase_admob: ^0.11.2
  # firebase_analyticss: ^6.2.0
  # firebase_crashlytics: ^0.2.3
  # firebase_ml_vision: ^0.9.8
  cloud_firestore: ^2.2.2

  #
  # Login & App Store packages
  #
  google_sign_in: ^5.0.4
  flutter_facebook_login: ^3.0.0
  sign_in_with_apple: ^3.0.0

  #
  # State managers
  #
  flutter_form_bloc: ^0.20.5

  #
  # Code structure, connectivity & internal services
  #
  flutter_localized_locales: ^2.0.2 #!!!!! ELIMINAR !!!!!!
  json_annotation: ^4.0.1 # Para la serializacion de objetos
  freezed_annotation: ^0.14.2
  url_launcher: ^6.0.7
  camera: ^0.8.1+3
  image_picker: ^0.8.1+1
  # multi_image_picker: ^4.6.1
  # file_picker: ^1.6.3+2
  agora_rtc_engine: ^4.0.2
  package_info: ^2.0.2
  # device_info: ^0.4.2+4 # Para obtener información del dispositivo
  permission_handler: ^8.1.1
  excel: ^2.0.0-null-safety-3

  #
  # Informing User / Loading
  #

  #
  # UI related packages
  #
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.1.0
  flutter_svg: ^0.22.0
  cached_network_image: ^3.0.0
  charts_flutter: ^0.10.0
  table_calendar: ^3.0.0
  smooth_page_indicator: ^0.2.3
  flutter_map: ^0.13.1
  flutter_colorpicker: ^0.5.0
  emoji_picker_flutter: ^1.0.6 # Emojies

  #
  # Social share packages
  #

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Para la serializacion de objetos
  build_runner: ^2.0.5
  built_value_generator: ^8.1.0
  injectable_generator: ^1.4.1
  freezed: ^0.14.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # generate: true

  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      # This plugin project was generated without specifying any
      # platforms with the `--platform` argument. If you see the `fake_platform` map below, remove it and
      # then add platforms following the instruction here:
      # https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
      # -------------------
      some_platform:
        pluginClass: somePluginClass
    # -------------------
    # To add assets to your plugin package, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    #
    # For details regarding assets in packages, see
    # https://flutter.dev/assets-and-images/#from-packages
    #
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # To add custom fonts to your plugin package, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts in packages, see
    # https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  # Tutorial: https://www.youtube.com/watch?v=icTT6xUYHow&t=8s
  enabled: true

  # Optional
  # Default: en
  # <lenguage code>[_<script code>][_<country code>]
  main_locale: es_ES

  # Optional
  # Default: S
  # Suggested alternative name: AppLocalizations
  class_name: HiveCoreString
