name: hive_core
description: A new flutter plugin project.
version: 0.0.1
author:
# homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.3
  # firebase_auth: ^0.18.4+1
  # firebase_auth_web: ^0.3.2+3
  # firebase_storage: ^5.2.0
  # firebase_messaging: ^7.0.3
  # firebase_admob: ^0.10.3
  # firebase_analyticss: ^6.2.0
  # firebase_crashlytics: ^0.2.3
  # firebase_ml_vision: ^0.9.8
  cloud_firestore: ^0.14.4
  google_sign_in: ^4.5.6

  agora_rtc_engine: ^1.0.13
  permission_handler: ^5.0.1+1

  path_provider: ^1.6.27
  json_annotation: # Para la serializacion de objetos

  flutter_form_bloc: ^0.19.0
  shared_preferences: ^0.5.12+4
  flutter_localized_locales:

  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.11.0
  emoji_picker: ^0.1.0 # Emojies
  charts_flutter: ^0.9.0 # Para dibujar graficos
  smooth_page_indicator: ^0.2.0 # Indicadores de PageView

  package_info: ^0.4.3+2
  # device_info: ^0.4.2+4                                # Para obtener información del dispositivo

  url_launcher: ^5.7.10
  cached_network_image: ^2.5.0
  flutter_svg: ^0.19.1
  image_picker: ^0.6.7+21
  camera: ^0.6.4+5
  # multi_image_picker: ^4.6.1
  # file_picker: ^1.6.3+2

  # local storage
  hive: ^1.4.4+1
  sqflite: ^1.3.2+1

  flutter_colorpicker: ^0.3.5
  flutter_map: ^0.10.1+1
  table_calendar: ^2.3.3
  excel: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      # This plugin project was generated without specifying any
      # platforms with the `--platform` argument. If you see the `fake_platform` map below, remove it and
      # then add platforms following the instruction here:
      # https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
      # -------------------
      some_platform:
        pluginClass: somePluginClass
    # -------------------
    # To add assets to your plugin package, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    #
    # For details regarding assets in packages, see
    # https://flutter.dev/assets-and-images/#from-packages
    #
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # To add custom fonts to your plugin package, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts in packages, see
    # https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  # Tutorial: https://www.youtube.com/watch?v=icTT6xUYHow&t=8s
  enabled: true

  # Optional
  # Default: en
  # <lenguage code>[_<script code>][_<country code>]
  main_locale: es_ES

  # Optional
  # Default: S
  # Suggested alternative name: AppLocalizations
  class_name: HiveCoreString
